### ISSUE TITLE
Síntesis-de-calidad

### ISSUE THREAD

**Issue by Brisa-4** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-Brisa-4#1]
[Síntesis.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-Brisa-4/files/9577328/Sintesis.pdf)

**Comment by Ferch0419** [comment]
Buen trabajo: 20/20.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
